name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci --audit false --fund false
        shell: bash
      - run: npm run build
        shell: bash
      - run: npm run test
        shell: bash